/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Interest from './Interest';

/**
* The AllOfUserInterest model module.
* @module model/AllOfUserInterest
* @version 0.0.1
*/
export default class AllOfUserInterest {
    /**
    * Constructs a new <code>AllOfUserInterest</code>.
    * @alias module:model/AllOfUserInterest
    * @class
    * @extends module:model/Interest
    * @param id {} Like never you saw an id lol
    * @param name {} Name of THE intrerest ^_^
    */

    constructor(id, name) {
        Interest.call(this, id, name);
        
        
    }

    /**
    * Constructs a <code>AllOfUserInterest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AllOfUserInterest} obj Optional instance to populate.
    * @return {module:model/AllOfUserInterest} The populated <code>AllOfUserInterest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllOfUserInterest();
            
            Interest.constructFromObject(data, obj);
            
        }
        return obj;
    }





}
