/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Role from './Role';

/**
 * The AllOfUserRole model module.
 * @module model/AllOfUserRole
 * @version 0.0.1
 */
export default class AllOfUserRole {
	/**
	 * Constructs a new <code>AllOfUserRole</code>.
	 * @alias module:model/AllOfUserRole
	 * @class
	 * @extends module:model/Role
	 * @param id {} Like never you saw an id lol
	 * @param name {} Name of the role simple...
	 */

	constructor(id, name) {
		Role.call(this, id, name);
	}

	/**
	 * Constructs a <code>AllOfUserRole</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/AllOfUserRole} obj Optional instance to populate.
	 * @return {module:model/AllOfUserRole} The populated <code>AllOfUserRole</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new AllOfUserRole();

			Role.constructFromObject(data, obj);
		}
		return obj;
	}
}
