/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Theme from './Theme';

/**
 * The AllOfUserTheme model module.
 * @module model/AllOfUserTheme
 * @version 0.0.1
 */
export default class AllOfUserTheme {
	/**
	 * Constructs a new <code>AllOfUserTheme</code>.
	 * @alias module:model/AllOfUserTheme
	 * @class
	 * @extends module:model/Theme
	 * @param id {} ID of the theme entity
	 * @param name {} Name of the theme
	 */

	constructor(id, name) {
		Theme.call(this, id, name);
	}

	/**
	 * Constructs a <code>AllOfUserTheme</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/AllOfUserTheme} obj Optional instance to populate.
	 * @return {module:model/AllOfUserTheme} The populated <code>AllOfUserTheme</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new AllOfUserTheme();

			Theme.constructFromObject(data, obj);
		}
		return obj;
	}
}
