/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Article from './Article';Object

/**
 * The AllOfCommentArticle model module.
 * @module model/AllOfCommentArticle
 * @version 0.0.1
 */
export default class AllOfCommentArticle {
	/**
	 * Constructs a new <code>AllOfCommentArticle</code>.
	 * @alias module:model/AllOfCommentArticle
	 * @class
	 * @extends module:model/Article
	 * @param id {} Id of the article
	 * @param title {} Title of the article
	 * @param content {} Content of the article
	 * @param createdAt {} Creation date of the article
	 * @param updatedAt {} Update date of the article
	 * @param dislikesList {} List of dislikes' authors ids
	 * @param likesList {} List of likes' authors ids
	 * @param category {}
	 * @param author {}
	 * @param coverImage {} Cover image link of the article
	 */

	constructor(
		id,
		title,
		content,
		createdAt,
		updatedAt,
		dislikesList,
		likesList,
		category,
		author,
		coverImage
	) {
		Article.call(
			this,
			id,
			title,
			content,
			createdAt,
			updatedAt,
			dislikesList,
			likesList,
			category,
			author,
			coverImage
		);
	}

	/**
	 * Constructs a <code>AllOfCommentArticle</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/AllOfCommentArticle} obj Optional instance to populate.
	 * @return {module:model/AllOfCommentArticle} The populated <code>AllOfCommentArticle</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new AllOfCommentArticle();

			Article.constructFromObject(data, obj);
		}
		return obj;
	}
}
