/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';Object

/**
 * The Clipboard model module.
 * @module model/Clipboard
 * @version 0.0.1
 */
export default class Clipboard {
	/**
	 * Constructs a new <code>Clipboard</code>.
	 * @alias module:model/Clipboard
	 * @class
	 * @param id {String} Id of the clipboard
	 * @param user {}
	 * @param articles {}
	 */

	constructor(id, user, articles) {
		this['id'] = id;
		this['user'] = user;
		this['articles'] = articles;
	}

	/**
	 * Constructs a <code>Clipboard</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/Clipboard} obj Optional instance to populate.
	 * @return {module:model/Clipboard} The populated <code>Clipboard</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new Clipboard();

			if (data.hasOwnProperty('id')) {
				obj['id'] = ApiClient.convertToType(data['id'], 'String');
			}
			if (data.hasOwnProperty('user')) {
				obj['user'] = ApiClient.convertToType(data['user'], Object);
			}
			if (data.hasOwnProperty('articles')) {
				obj['articles'] = ApiClient.convertToType(
					data['articles'],
					Object
				);
			}
		}
		return obj;
	}

	/**
	 * Id of the clipboard
	 * @member {String} id
	 */
	id = undefined;
	/**
	 * @member {} user
	 */
	user = undefined;
	/**
	 * @member {} articles
	 */
	articles = undefined;
}
