/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateCommentDto model module.
 * @module model/CreateCommentDto
 * @version 0.0.1
 */
export default class CreateCommentDto {
	/**
	 * Constructs a new <code>CreateCommentDto</code>.
	 * @alias module:model/CreateCommentDto
	 * @class
	 * @param articleId {String} Id of the commented article
	 * @param authorId {String} Id of the author of the comment
	 * @param content {String} Content of the comment
	 */

	constructor(articleId, authorId, content) {
		this['articleId'] = articleId;
		this['authorId'] = authorId;
		this['content'] = content;
	}

	/**
	 * Constructs a <code>CreateCommentDto</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/CreateCommentDto} obj Optional instance to populate.
	 * @return {module:model/CreateCommentDto} The populated <code>CreateCommentDto</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new CreateCommentDto();

			if (data.hasOwnProperty('articleId')) {
				obj['articleId'] = ApiClient.convertToType(data['articleId'], 'String');
			}
			if (data.hasOwnProperty('authorId')) {
				obj['authorId'] = ApiClient.convertToType(data['authorId'], 'String');
			}
			if (data.hasOwnProperty('content')) {
				obj['content'] = ApiClient.convertToType(data['content'], 'String');
			}
		}
		return obj;
	}

	/**
	 * Id of the commented article
	 * @member {String} articleId
	 */
	articleId = undefined;
	/**
	 * Id of the author of the comment
	 * @member {String} authorId
	 */
	authorId = undefined;
	/**
	 * Content of the comment
	 * @member {String} content
	 */
	content = undefined;
}
