/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateNotificationDto model module.
* @module model/CreateNotificationDto
* @version 0.0.1
*/
export default class CreateNotificationDto {
    /**
    * Constructs a new <code>CreateNotificationDto</code>.
    * @alias module:model/CreateNotificationDto
    * @class
    * @param content {String} Content of the notification
    * @param senderId {String} Id of the notificaton sender
    * @param recipientId {String} Id of the notificaton recipient
    */

    constructor(content, senderId, recipientId) {
        
        
        this['content'] = content;
        this['senderId'] = senderId;
        this['recipientId'] = recipientId;
        
    }

    /**
    * Constructs a <code>CreateNotificationDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateNotificationDto} obj Optional instance to populate.
    * @return {module:model/CreateNotificationDto} The populated <code>CreateNotificationDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateNotificationDto();
                        
            
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('senderId')) {
                obj['senderId'] = ApiClient.convertToType(data['senderId'], 'String');
            }
            if (data.hasOwnProperty('recipientId')) {
                obj['recipientId'] = ApiClient.convertToType(data['recipientId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Content of the notification
    * @member {String} content
    */
    'content' = undefined;
    /**
    * Id of the notificaton sender
    * @member {String} senderId
    */
    'senderId' = undefined;
    /**
    * Id of the notificaton recipient
    * @member {String} recipientId
    */
    'recipientId' = undefined;




}
