/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateArticleDto model module.
 * @module model/CreateArticleDto
 * @version 0.0.1
 */
export default class CreateArticleDto {
	/**
	 * Constructs a new <code>CreateArticleDto</code>.
	 * @alias module:model/CreateArticleDto
	 * @class
	 * @param title {String} Title of the article
	 * @param content {String} Content of the article
	 * @param authorId {String} Id of the author of the article
	 * @param coverImage {String} Cover image link of the article
	 */

	constructor(title, content, authorId, coverImage) {
		this['title'] = title;
		this['content'] = content;
		this['authorId'] = authorId;
		this['coverImage'] = coverImage;
	}

	/**
	 * Constructs a <code>CreateArticleDto</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/CreateArticleDto} obj Optional instance to populate.
	 * @return {module:model/CreateArticleDto} The populated <code>CreateArticleDto</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new CreateArticleDto();

			if (data.hasOwnProperty('title')) {
				obj['title'] = ApiClient.convertToType(data['title'], 'String');
			}
			if (data.hasOwnProperty('content')) {
				obj['content'] = ApiClient.convertToType(data['content'], 'String');
			}
			if (data.hasOwnProperty('authorId')) {
				obj['authorId'] = ApiClient.convertToType(data['authorId'], 'String');
			}
			if (data.hasOwnProperty('categoryId')) {
				obj['categoryId'] = ApiClient.convertToType(
					data['categoryId'],
					'String'
				);
			}
			if (data.hasOwnProperty('coverImage')) {
				obj['coverImage'] = ApiClient.convertToType(
					data['coverImage'],
					'String'
				);
			}
		}
		return obj;
	}

	/**
	 * Title of the article
	 * @member {String} title
	 */
	title = undefined;
	/**
	 * Content of the article
	 * @member {String} content
	 */
	content = undefined;
	/**
	 * Id of the author of the article
	 * @member {String} authorId
	 */
	authorId = undefined;
	/**
	 * Id of the category
	 * @member {String} categoryId
	 */
	categoryId = undefined;
	/**
	 * Cover image link of the article
	 * @member {String} coverImage
	 */
	coverImage = undefined;
}
