/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateClipboardDto model module.
* @module model/CreateClipboardDto
* @version 0.0.1
*/
export default class CreateClipboardDto {
    /**
    * Constructs a new <code>CreateClipboardDto</code>.
    * @alias module:model/CreateClipboardDto
    * @class
    * @param userId {String} Id of the user
    * @param articlesIds {Array.<String>} Ids of the articles
    */

    constructor(userId, articlesIds) {
        
        
        this['userId'] = userId;
        this['articlesIds'] = articlesIds;
        
    }

    /**
    * Constructs a <code>CreateClipboardDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateClipboardDto} obj Optional instance to populate.
    * @return {module:model/CreateClipboardDto} The populated <code>CreateClipboardDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateClipboardDto();
                        
            
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('articlesIds')) {
                obj['articlesIds'] = ApiClient.convertToType(data['articlesIds'], ['String']);
            }
        }
        return obj;
    }

    /**
    * Id of the user
    * @member {String} userId
    */
    userId = undefined;
    /**
    * Ids of the articles
    * @member {Array.<String>} articlesIds
    */
    articlesIds = undefined;




}
