/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateUserDto model module.
* @module model/CreateUserDto
* @version 0.0.1
*/
export default class CreateUserDto {
    /**
    * Constructs a new <code>CreateUserDto</code>.
    * @alias module:model/CreateUserDto
    * @class
    * @param name {String} User name
    * @param lastName {String} User lastname
    * @param email {String} User email adress
    * @param passwordHash {String} User password
    * @param roleId {String} id of role
    * @param themeId {String} id of theme
    */

    constructor(name, lastName, email, passwordHash, roleId, themeId) {
        
        
        this['name'] = name;
        this['lastName'] = lastName;
        this['email'] = email;
        this['passwordHash'] = passwordHash;
        this['roleId'] = roleId;
        this['themeId'] = themeId;
        
    }

    /**
    * Constructs a <code>CreateUserDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateUserDto} obj Optional instance to populate.
    * @return {module:model/CreateUserDto} The populated <code>CreateUserDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserDto();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('passwordHash')) {
                obj['passwordHash'] = ApiClient.convertToType(data['passwordHash'], 'String');
            }
            if (data.hasOwnProperty('roleId')) {
                obj['roleId'] = ApiClient.convertToType(data['roleId'], 'String');
            }
            if (data.hasOwnProperty('interestId')) {
                obj['interestId'] = ApiClient.convertToType(data['interestId'], 'String');
            }
            if (data.hasOwnProperty('clipboardId')) {
                obj['clipboardId'] = ApiClient.convertToType(data['clipboardId'], 'String');
            }
            if (data.hasOwnProperty('themeId')) {
                obj['themeId'] = ApiClient.convertToType(data['themeId'], 'String');
            }
        }
        return obj;
    }

    /**
    * User name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * User lastname
    * @member {String} lastName
    */
    'lastName' = undefined;
    /**
    * User email adress
    * @member {String} email
    */
    'email' = undefined;
    /**
    * User password
    * @member {String} passwordHash
    */
    'passwordHash' = undefined;
    /**
    * id of role
    * @member {String} roleId
    */
    'roleId' = undefined;
    /**
    * id of interest
    * @member {String} interestId
    */
    'interestId' = undefined;
    /**
    * id of clipboard
    * @member {String} clipboardId
    */
    'clipboardId' = undefined;
    /**
    * id of theme
    * @member {String} themeId
    */
    'themeId' = undefined;




}
