/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateBannedUserDto model module.
* @module model/CreateBannedUserDto
* @version 0.0.1
*/
export default class CreateBannedUserDto {
    /**
    * Constructs a new <code>CreateBannedUserDto</code>.
    * @alias module:model/CreateBannedUserDto
    * @class
    * @param reason {String} Reason why user is banned
    * @param userId {String} Banned user id
    */

    constructor(reason, userId) {
        
        
        this['reason'] = reason;
        this['userId'] = userId;
        
    }

    /**
    * Constructs a <code>CreateBannedUserDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateBannedUserDto} obj Optional instance to populate.
    * @return {module:model/CreateBannedUserDto} The populated <code>CreateBannedUserDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBannedUserDto();
                        
            
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Reason why user is banned
    * @member {String} reason
    */
    reason = undefined;
    /**
    * Banned user id
    * @member {String} userId
    */
    userId = undefined;




}
