/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse201 model module.
 * @module model/InlineResponse201
 * @version 0.0.1
 */
export default class InlineResponse201 {
	/**
	 * Constructs a new <code>InlineResponse201</code>.
	 * @alias module:model/InlineResponse201
	 * @class
	 */

	constructor() {}

	/**
	 * Constructs a <code>InlineResponse201</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/InlineResponse201} obj Optional instance to populate.
	 * @return {module:model/InlineResponse201} The populated <code>InlineResponse201</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new InlineResponse201();

			if (data.hasOwnProperty('id')) {
				obj['id'] = ApiClient.convertToType(data['id'], 'String');
			}
		}
		return obj;
	}

	/**
	 * ID of the created entity
	 * @member {String} id
	 */
	id = undefined;
}
