/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginUserDto model module.
 * @module model/LoginUserDto
 * @version 0.0.1
 */
export default class LoginUserDto {
	/**
	 * Constructs a new <code>LoginUserDto</code>.
	 * @alias module:model/LoginUserDto
	 * @class
	 * @param email {String} User email adress
	 * @param password {String} User password
	 */

	constructor(email, password) {
		this['email'] = email;
		this['password'] = password;
	}

	/**
	 * Constructs a <code>LoginUserDto</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/LoginUserDto} obj Optional instance to populate.
	 * @return {module:model/LoginUserDto} The populated <code>LoginUserDto</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new LoginUserDto();

			if (data.hasOwnProperty('email')) {
				obj['email'] = ApiClient.convertToType(data['email'], 'String');
			}
			if (data.hasOwnProperty('password')) {
				obj['password'] = ApiClient.convertToType(data['password'], 'String');
			}
		}
		return obj;
	}

	/**
	 * User email adress
	 * @member {String} email
	 */
	email = undefined;
	/**
	 * User password
	 * @member {String} password
	 */
	password = undefined;
}
