/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Theme model module.
* @module model/Theme
* @version 0.0.1
*/
export default class Theme {
    /**
    * Constructs a new <code>Theme</code>.
    * @alias module:model/Theme
    * @class
    * @param id {String} ID of the theme entity
    * @param name {String} Name of the theme
    */

    constructor(id, name) {
        
        
        this['id'] = id;
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>Theme</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Theme} obj Optional instance to populate.
    * @return {module:model/Theme} The populated <code>Theme</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Theme();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * ID of the theme entity
    * @member {String} id
    */
    id = undefined;
    /**
    * Name of the theme
    * @member {String} name
    */
    name = undefined;




}
