/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UpdateArticleDto model module.
* @module model/UpdateArticleDto
* @version 0.0.1
*/
export default class UpdateArticleDto {
    /**
    * Constructs a new <code>UpdateArticleDto</code>.
    * @alias module:model/UpdateArticleDto
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateArticleDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateArticleDto} obj Optional instance to populate.
    * @return {module:model/UpdateArticleDto} The populated <code>UpdateArticleDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateArticleDto();
                        
            
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Title of the article
    * @member {String} title
    */
    title = undefined;
    /**
    * Content of the article
    * @member {String} content
    */
    content = undefined;
    /**
    * Id of the category
    * @member {String} categoryId
    */
    categoryId = undefined;




}
