/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UpdateClipboardDto model module.
* @module model/UpdateClipboardDto
* @version 0.0.1
*/
export default class UpdateClipboardDto {
    /**
    * Constructs a new <code>UpdateClipboardDto</code>.
    * @alias module:model/UpdateClipboardDto
    * @class
    * @param articleId {String} Id of the article
    */

    constructor(articleId) {
        
        
        this['articleId'] = articleId;
        
    }

    /**
    * Constructs a <code>UpdateClipboardDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateClipboardDto} obj Optional instance to populate.
    * @return {module:model/UpdateClipboardDto} The populated <code>UpdateClipboardDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateClipboardDto();
                        
            
            if (data.hasOwnProperty('articleId')) {
                obj['articleId'] = ApiClient.convertToType(data['articleId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Id of the article
    * @member {String} articleId
    */
    'articleId' = undefined;




}
