/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UploadImageDto model module.
 * @module model/UploadImageDto
 * @version 0.0.1
 */
export default class UploadImageDto {
	/**
	 * Constructs a new <code>UploadImageDto</code>.
	 * @alias module:model/UploadImageDto
	 * @class
	 * @param file {File} File to be uploaded
	 * @param uploadedBy {String} Id of the user who uploaded the image
	 */

	constructor(file, uploadedBy) {
		this['file'] = file;
		this['uploadedBy'] = uploadedBy;
	}

	/**
	 * Constructs a <code>UploadImageDto</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/UploadImageDto} obj Optional instance to populate.
	 * @return {module:model/UploadImageDto} The populated <code>UploadImageDto</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new UploadImageDto();

			if (data.hasOwnProperty('file')) {
				obj['file'] = ApiClient.convertToType(data['file'], File);
			}
			if (data.hasOwnProperty('uploadedBy')) {
				obj['uploadedBy'] = ApiClient.convertToType(
					data['uploadedBy'],
					'String'
				);
			}
		}
		return obj;
	}

	/**
	 * File to be uploaded
	 * @member {File} file
	 */
	file = undefined;
	/**
	 * Id of the user who uploaded the image
	 * @member {String} uploadedBy
	 */
	uploadedBy = undefined;
}
