/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 0.0.1
 */
export default class User {
	/**
	 * Constructs a new <code>User</code>.
	 * @alias module:model/User
	 * @class
	 * @param id {String} ID of the user entity
	 * @param name {String} User name
	 * @param lastName {String} User lastname
	 * @param email {String} User email adress
	 * @param passwordHash {String} User password
	 * @param role {}
	 * @param theme {}
	 */

	constructor(id, name, lastName, email, passwordHash, role, theme) {
		this['id'] = id;
		this['name'] = name;
		this['lastName'] = lastName;
		this['email'] = email;
		this['passwordHash'] = passwordHash;
		this['role'] = role;
		this['theme'] = theme;
	}

	/**
	 * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/User} obj Optional instance to populate.
	 * @return {module:model/User} The populated <code>User</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new User();

			if (data.hasOwnProperty('id')) {
				obj['id'] = ApiClient.convertToType(data['id'], 'String');
			}
			if (data.hasOwnProperty('name')) {
				obj['name'] = ApiClient.convertToType(data['name'], 'String');
			}
			if (data.hasOwnProperty('lastName')) {
				obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
			}
			if (data.hasOwnProperty('email')) {
				obj['email'] = ApiClient.convertToType(data['email'], 'String');
			}
			if (data.hasOwnProperty('passwordHash')) {
				obj['passwordHash'] = ApiClient.convertToType(data['passwordHash'], 'String');
			}
			if (data.hasOwnProperty('role')) {
				obj['role'] = ApiClient.convertToType(data['role'], Object);
			}
			if (data.hasOwnProperty('interest')) {
				obj['interest'] = ApiClient.convertToType(data['interest'], Object);
			}
			if (data.hasOwnProperty('theme')) {
				obj['theme'] = ApiClient.convertToType(data['theme'], Object);
			}
		}
		return obj;
	}

	/**
	 * ID of the user entity
	 * @member {String} id
	 */
	id = undefined;
	/**
	 * User name
	 * @member {String} name
	 */
	name = undefined;
	/**
	 * User lastname
	 * @member {String} lastName
	 */
	lastName = undefined;
	/**
	 * User email adress
	 * @member {String} email
	 */
	email = undefined;
	/**
	 * User password
	 * @member {String} passwordHash
	 */
	passwordHash = undefined;
	/**
	 * @member {} role
	 */
	role = undefined;
	/**
	 * @member {} interest
	 */
	interest = undefined;
	/**
	 * @member {} theme
	 */
	theme = undefined;
}
