/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import BannedArticle from '../model/BannedArticle';
import CreateBannedArticleDto from '../model/CreateBannedArticleDto';
import InlineResponse201 from '../model/InlineResponse201';
import InlineResponse404 from '../model/InlineResponse404';
import InlineResponse4041 from '../model/InlineResponse4041';

/**
* BannedArticle service.
* @module api/BannedArticleApi
* @version 0.0.1
*/
export default class BannedArticleApi {

    /**
    * Constructs a new BannedArticleApi. 
    * @alias module:api/BannedArticleApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the bannedArticleControllerBanArticle operation.
     * @callback module:api/BannedArticleApi~bannedArticleControllerBanArticleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse201} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new banned article
     * @param {module:api/BannedArticleApi~bannedArticleControllerBanArticleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse201}
     */
    bannedArticleControllerBanArticle(body, callback) {
      let postBody = body;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse201;

      return this.apiClient.callApi(
        '/api/v1/bannedArticle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the bannedArticleControllerFindBannedArticle operation.
     * @callback module:api/BannedArticleApi~bannedArticleControllerFindBannedArticleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BannedArticle} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns banned article details
     * @param {module:api/BannedArticleApi~bannedArticleControllerFindBannedArticleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BannedArticle}
     */
    bannedArticleControllerFindBannedArticle(id, callback) {
      let postBody = null;

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BannedArticle;

      return this.apiClient.callApi(
        '/api/v1/bannedArticle/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
