/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Comment from '../model/Comment';
import CreateCommentDto from '../model/CreateCommentDto';
import InlineResponse201 from '../model/InlineResponse201';
import InlineResponse4045 from '../model/InlineResponse4045';
import InlineResponse4048 from '../model/InlineResponse4048';
import InlineResponse4049 from '../model/InlineResponse4049';

/**
 * Comments service.
 * @module api/CommentsApi
 * @version 0.0.1
 */
export default class CommentsApi {
	/**
	 * Constructs a new CommentsApi.
	 * @alias module:api/CommentsApi
	 * @class
	 * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
	 * default to {@link module:ApiClient#instance} if unspecified.
	 */
	constructor(apiClient) {
		this.apiClient = apiClient || ApiClient.instance;
	}

	/**
	 * Callback function to receive the result of the commentControllerCreate operation.
	 * @callback module:api/CommentsApi~commentControllerCreateCallback
	 * @param {String} error Error message, if any.
	 * @param {module:model/InlineResponse201} data The data returned by the service call.
	 * @param {String} response The complete HTTP response.
	 */

	/**
	 * Creates a new comment
	 * @param {module:api/CommentsApi~commentControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
	 * data is of type: {@link module:model/InlineResponse201}
	 */
	commentControllerCreate(body, callback) {
		let postBody = body;

		let pathParams = {};
		let queryParams = {};
		let headerParams = {};
		let formParams = {};

		let authNames = ['bearer'];
		let contentTypes = ['application/json'];
		let accepts = ['application/json'];
		let returnType = InlineResponse201;

		return this.apiClient.callApi(
			'/api/v1/comments',
			'POST',
			pathParams,
			queryParams,
			headerParams,
			formParams,
			postBody,
			authNames,
			contentTypes,
			accepts,
			returnType,
			callback
		);
	}
	/**
	 * Callback function to receive the result of the commentControllerFindByArticleId operation.
	 * @callback module:api/CommentsApi~commentControllerFindByArticleIdCallback
	 * @param {String} error Error message, if any.
	 * @param {Array.<module:model/Comment>} data The data returned by the service call.
	 * @param {String} response The complete HTTP response.
	 */

	/**
	 * Returns all comments by the given article id
	 * @param {module:api/CommentsApi~commentControllerFindByArticleIdCallback} callback The callback function, accepting three arguments: error, data, response
	 * data is of type: {@link Array.<module:model/Comment>}
	 */
	commentControllerFindByArticleId(id, callback) {
		let postBody = null;

		let pathParams = {
			id: id,
		};
		let queryParams = {};
		let headerParams = {};
		let formParams = {};

		let authNames = ['bearer'];
		let contentTypes = [];
		let accepts = ['application/json'];
		let returnType = [Comment];

		return this.apiClient.callApi(
			'/api/v1/comments/article/{id}',
			'GET',
			pathParams,
			queryParams,
			headerParams,
			formParams,
			postBody,
			authNames,
			contentTypes,
			accepts,
			returnType,
			callback
		);
	}
	/**
	 * Callback function to receive the result of the commentControllerFindByAuthorId operation.
	 * @callback module:api/CommentsApi~commentControllerFindByAuthorIdCallback
	 * @param {String} error Error message, if any.
	 * @param {Array.<module:model/Comment>} data The data returned by the service call.
	 * @param {String} response The complete HTTP response.
	 */

	/**
	 * Returns all comments by the given user id
	 * @param {module:api/CommentsApi~commentControllerFindByAuthorIdCallback} callback The callback function, accepting three arguments: error, data, response
	 * data is of type: {@link Array.<module:model/Comment>}
	 */
	commentControllerFindByAuthorId(id, callback) {
		let postBody = null;

		let pathParams = {
			id: id,
		};
		let queryParams = {};
		let headerParams = {};
		let formParams = {};

		let authNames = ['bearer'];
		let contentTypes = [];
		let accepts = ['application/json'];
		let returnType = [Comment];

		return this.apiClient.callApi(
			'/api/v1/comments/user/{id}',
			'GET',
			pathParams,
			queryParams,
			headerParams,
			formParams,
			postBody,
			authNames,
			contentTypes,
			accepts,
			returnType,
			callback
		);
	}
}
