/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateInterestDto from '../model/CreateInterestDto';
import InlineResponse201 from '../model/InlineResponse201';
import Interest from '../model/Interest';

/**
 * Interests service.
 * @module api/InterestsApi
 * @version 0.0.1
 */
export default class InterestsApi {
	/**
	 * Constructs a new InterestsApi.
	 * @alias module:api/InterestsApi
	 * @class
	 * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
	 * default to {@link module:ApiClient#instance} if unspecified.
	 */
	constructor(apiClient) {
		this.apiClient = apiClient || ApiClient.instance;
	}

	/**
	 * Callback function to receive the result of the interestControllerCreate operation.
	 * @callback module:api/InterestsApi~interestControllerCreateCallback
	 * @param {String} error Error message, if any.
	 * @param {module:model/InlineResponse201} data The data returned by the service call.
	 * @param {String} response The complete HTTP response.
	 */

	/**
	 * Creates a new interest
	 * @param {module:api/InterestsApi~interestControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
	 * data is of type: {@link module:model/InlineResponse201}
	 */
	interestControllerCreate(body, callback) {
		let postBody = body;

		let pathParams = {};
		let queryParams = {};
		let headerParams = {};
		let formParams = {};

		let authNames = ['bearer'];
		let contentTypes = ['application/json'];
		let accepts = ['application/json'];
		let returnType = InlineResponse201;

		return this.apiClient.callApi(
			'/api/v1/interests',
			'POST',
			pathParams,
			queryParams,
			headerParams,
			formParams,
			postBody,
			authNames,
			contentTypes,
			accepts,
			returnType,
			callback
		);
	}
	/**
	 * Callback function to receive the result of the interestControllerFindAll operation.
	 * @callback module:api/InterestsApi~interestControllerFindAllCallback
	 * @param {String} error Error message, if any.
	 * @param {Array.<module:model/Interest>} data The data returned by the service call.
	 * @param {String} response The complete HTTP response.
	 */

	/**
	 * Returns all interests
	 * @param {module:api/InterestsApi~interestControllerFindAllCallback} callback The callback function, accepting three arguments: error, data, response
	 * data is of type: {@link Array.<module:model/Interest>}
	 */
	interestControllerFindAll(callback) {
		let postBody = null;

		let pathParams = {};
		let queryParams = {};
		let headerParams = {};
		let formParams = {};

		let authNames = ['bearer'];
		let contentTypes = [];
		let accepts = ['application/json'];
		let returnType = [Interest];

		return this.apiClient.callApi(
			'/api/v1/interests',
			'GET',
			pathParams,
			queryParams,
			headerParams,
			formParams,
			postBody,
			authNames,
			contentTypes,
			accepts,
			returnType,
			callback
		);
	}
}
