/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateNotificationDto from '../model/CreateNotificationDto';
import InlineResponse201 from '../model/InlineResponse201';
import InlineResponse40411 from '../model/InlineResponse40411';
import InlineResponse40412 from '../model/InlineResponse40412';
import Notification from '../model/Notification';

/**
 * Notifications service.
 * @module api/NotificationsApi
 * @version 0.0.1
 */
export default class NotificationsApi {
	/**
	 * Constructs a new NotificationsApi.
	 * @alias module:api/NotificationsApi
	 * @class
	 * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
	 * default to {@link module:ApiClient#instance} if unspecified.
	 */
	constructor(apiClient) {
		this.apiClient = apiClient || ApiClient.instance;
	}

	/**
	 * Callback function to receive the result of the notificationControllerCreate operation.
	 * @callback module:api/NotificationsApi~notificationControllerCreateCallback
	 * @param {String} error Error message, if any.
	 * @param {module:model/InlineResponse201} data The data returned by the service call.
	 * @param {String} response The complete HTTP response.
	 */

	/**
	 * Creates a new notification
	 * @param {module:api/NotificationsApi~notificationControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
	 * data is of type: {@link module:model/InlineResponse201}
	 */
	notificationControllerCreate(body, callback) {
		let postBody = body;

		let pathParams = {};
		let queryParams = {};
		let headerParams = {};
		let formParams = {};

		let authNames = ['bearer'];
		let contentTypes = ['application/json'];
		let accepts = ['application/json'];
		let returnType = InlineResponse201;

		return this.apiClient.callApi(
			'/api/v1/notifications',
			'POST',
			pathParams,
			queryParams,
			headerParams,
			formParams,
			postBody,
			authNames,
			contentTypes,
			accepts,
			returnType,
			callback
		);
	}
	/**
	 * Callback function to receive the result of the notificationControllerFindByUserId operation.
	 * @callback module:api/NotificationsApi~notificationControllerFindByUserIdCallback
	 * @param {String} error Error message, if any.
	 * @param {Array.<module:model/Notification>} data The data returned by the service call.
	 * @param {String} response The complete HTTP response.
	 */

	/**
	 * Returns a list of all notifications by the given user id
	 * @param {module:api/NotificationsApi~notificationControllerFindByUserIdCallback} callback The callback function, accepting three arguments: error, data, response
	 * data is of type: {@link Array.<module:model/Notification>}
	 */
	notificationControllerFindByUserId(id, callback) {
		let postBody = null;

		let pathParams = {
			id: id,
		};
		let queryParams = {};
		let headerParams = {};
		let formParams = {};

		let authNames = ['bearer'];
		let contentTypes = [];
		let accepts = ['application/json'];
		let returnType = [Notification];

		return this.apiClient.callApi(
			'/api/v1/notifications/user/{id}',
			'GET',
			pathParams,
			queryParams,
			headerParams,
			formParams,
			postBody,
			authNames,
			contentTypes,
			accepts,
			returnType,
			callback
		);
	}
}
