/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnowYourPlaceApi);
  }
}(this, function(expect, KnowYourPlaceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnowYourPlaceApi.CreateUserDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateUserDto', function() {
    it('should create an instance of CreateUserDto', function() {
      // uncomment below and update the code to test CreateUserDto
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be.a(KnowYourPlaceApi.CreateUserDto);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

    it('should have the property passwordHash (base name: "passwordHash")', function() {
      // uncomment below and update the code to test the property passwordHash
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

    it('should have the property roleId (base name: "roleId")', function() {
      // uncomment below and update the code to test the property roleId
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

    it('should have the property interestId (base name: "interestId")', function() {
      // uncomment below and update the code to test the property interestId
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

    it('should have the property clipboardId (base name: "clipboardId")', function() {
      // uncomment below and update the code to test the property clipboardId
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

    it('should have the property themeId (base name: "themeId")', function() {
      // uncomment below and update the code to test the property themeId
      //var instane = new KnowYourPlaceApi.CreateUserDto();
      //expect(instance).to.be();
    });

  });

}));
