/**
 * KnowYourPlace API
 * API do 'Aplikacja dla studentów zagranicznych'.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnowYourPlaceApi);
  }
}(this, function(expect, KnowYourPlaceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnowYourPlaceApi.ArticlesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticlesApi', function() {
    describe('articleControllerCreate', function() {
      it('should call articleControllerCreate successfully', function(done) {
        //uncomment below and update the code to test articleControllerCreate
        //instance.articleControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleControllerFindById', function() {
      it('should call articleControllerFindById successfully', function(done) {
        //uncomment below and update the code to test articleControllerFindById
        //instance.articleControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleControllerFindByPhrase', function() {
      it('should call articleControllerFindByPhrase successfully', function(done) {
        //uncomment below and update the code to test articleControllerFindByPhrase
        //instance.articleControllerFindByPhrase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleControllerUpdate', function() {
      it('should call articleControllerUpdate successfully', function(done) {
        //uncomment below and update the code to test articleControllerUpdate
        //instance.articleControllerUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleControllerUpdateDislikesById', function() {
      it('should call articleControllerUpdateDislikesById successfully', function(done) {
        //uncomment below and update the code to test articleControllerUpdateDislikesById
        //instance.articleControllerUpdateDislikesById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleControllerUpdateLikesById', function() {
      it('should call articleControllerUpdateLikesById successfully', function(done) {
        //uncomment below and update the code to test articleControllerUpdateLikesById
        //instance.articleControllerUpdateLikesById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
